spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/alibi
#    username: alibi
#    password: alibi
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      minimum-idle: 50
#      maximum-pool-size: 200
#      idle-timeout: 120000
#      leak-detection-threshold: 60000
#      max-lifetime: 50000
  threads:
    virtual:
      enabled: true

#app:
#  kafka:
#    bootstrap-server: localhost:29092
#    topic:
#      sashok: sashok-topic
#    group:
#      step: step_group_id
#      cassandra: cassandra_group_id

sashok:
  kafka:
    bootstrap-server: localhost:29092
    topic: sashok-topic
