spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alibi
    username: alibi
    password: alibi
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 50
      maximum-pool-size: 200
      idle-timeout: 120000
      leak-detection-threshold: 60000
      max-lifetime: 50000
  threads:
    virtual:
      enabled: true
  kafka:
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      max-poll-records: 1
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: localhost:29092
    producer:
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:29092

server:
  tomcat:
    threads:
      max: 1000
      min-spare: 400
    connection-timeout: 60000
  port: 8088

logging:
  level:
    org:
      springframework:
        web: DEBUG

app:
  kafka:
    bootstrap-servers: localhost:29092
    topic:
      sashok: sashok-topic
      thirty-min-retry: thirty-min-retry-topic
      one-hours-retry: one-hours-retry-topic
      two-hour-retry: two-hour-retry-topic
      four-hours-retry: four-hours-retry-topic
      eight-hours-retry: eight-hours-retry-topic
      sixteen-hours-retry: sixteen-hours-retry-topic
      thirty-hours-retry: thirty-hours-retry-topic
      five-days-retry: five-days-retry-topic
    group:
      step: step_group_id
      cassandra: cassandra_group_id
      thirty-min-retry: thirty_min_retry_group_id
      one-hours-retry: one-hours_retry_group_id
      two-hour-retry: two_hour_retry_group_id
      four-hours-retry: four_hours_retry_group_id
      eight-hours-retry: eight_hours_retry_group_id
      sixteen-hours-retry: sixteen_hours_retry_group_id
      thirty-hours-retry: thirty_hours_retry_group_id
      five-days-retry: five_days_retry_group_id
