spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alibi
    username: alibi
    password: alibi
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 25
      maximum-pool-size: 100
      idle-timeout: 60000
      leak-detection-threshold: 30000
      max-lifetime: 25000
  threads:
    virtual:
      enabled: true

server:
  tomcat:
    threads:
      max: 1000
      min-spare: 400
    connection-timeout: 60000
  port: 8088

logging:
  level:
    org:
      springframework:
        web: DEBUG

app:
  kafka:
    topic: sashok-topic
    step-group: step_group_id
    cassandra-group: cassandra_group_id